---
recon:
  git_repo: 'https://github.com/DigitalScriptorium/ds-data.git'
  git_branch: main
  git_local_name: ds-data
  iiif_manifests: iiif/legacy-iiif-manifests.csv
  # TODO: make sets a hash so you can do Settings.recon.sets.genres
  splits:
    columns:

  sets:
    - name: names
      repo_path: terms/reconciled/names.csv
      key_column: name_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      # balanced columns should have equal numbers of non-blank subfields in
      # each row; e.g.,
      #
      # structured_value,authorized_label
      # a|b,c|d
      # 1|2|3,x|y|z
      # r,s
      balanced_columns:
        - structured_value
        - authorized_label
        - instance_of
    - name: genres
      repo_path: terms/reconciled/genres.csv
      key_column: genre_as_recorded
      subset_column: vocabulary
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: materials
      repo_path: terms/reconciled/materials.csv
      key_column: material_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: languages
      repo_path: terms/reconciled/languages.csv
      key_column: language_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: places
      repo_path: terms/reconciled/places.csv
      key_column: place_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: subjects
      repo_path: terms/reconciled/subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: named-subjects
      repo_path: terms/reconciled/named-subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: all-subjects
      repo_path:
        - terms/reconciled/subjects.csv
        - terms/reconciled/named-subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value
      authorized_label_column: authorized_label
      balanced_columns:
        - structured_value
        - authorized_label
    - name: titles
      repo_path: terms/reconciled/titles.csv
      key_column: title_as_recorded
      structured_data_column: authorized_label
    - name: splits
      repo_path: terms/reconciled/splits.csv
      key_column: as_recorded
      structured_data_column: authorized_label