---
recon:
  git_repo: 'https://github.com/DigitalScriptorium/ds-data.git'
  git_branch: 'main'
  git_local_name: 'ds-data'
  sets:
    - name: names
      repo_path: terms/names.csv
      key_column: name_as_recorded
      structured_data_column: structured_value
    - name: genres
      repo_path: terms/genres.csv
      key_column: genre_as_recorded
      subset_column: vocabulary
      structured_data_column: structured_value
    - name: materials
      repo_path: terms/materials.csv
      key_column: material_as_recorded
      structured_data_column: structured_value
    - name: languages
      repo_path: terms/languages.csv
      key_column: language_as_recorded
      structured_data_column: structured_value
    - name: places
      repo_path: terms/places.csv
      key_column: place_as_recorded
      structured_data_column: structured_value
    - name: subjects
      repo_path: terms/subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value
    - name: named-subjects
      repo_path: terms/named-subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value
    - name: all-subjects
      repo_path:
        - terms/subjects.csv
        - terms/named-subjects.csv
      key_column: subject_as_recorded
      structured_data_column: structured_value